# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

env:
  GIN_MODE: release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      checks: write

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version-file: 'go.mod'
        cache: true

    - name: Revive Action
      uses: morphy2k/revive-action@v2.4.1

    - name: Run run script (trace)
      shell: bash
      env:
        GIN_MODE: release
        DEBUG: ""
        IGNORE_LOCAL_GO: ""
        GO_VERSION: 1.19.x
      run: |
        set -Eeuo pipefail
        echo "PWD: $(pwd)"
        echo "BASH version: $BASH_VERSION"
        echo "Env: GIN_MODE=${GIN_MODE:-}, DEBUG=${DEBUG:-}, IGNORE_LOCAL_GO=${IGNORE_LOCAL_GO:-}, GO_VERSION=${GO_VERSION:-}"
        ls -la
        file src/run || true
        sed -n '1,5p' src/run || true
        echo "--- START RUN ---"
        bash -x src/run
        echo "--- END RUN ---"

    - name: Staticcheck
      uses: dominikh/staticcheck-action@v1.3.0

    - name: Build
      run: |
        go mod download
        go install gotest.tools/gotestsum@latest

    - name: Test
      run: |
        gotestsum --format=standard-verbose --junitfile=junit.xml

    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v3
      if: success() || failure() # always run even if the previous step fails
      with:
        report_paths: '**/junit.xml'
        detailed_summary: true
        include_passed: true
