# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

env:
  GIN_MODE: release

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      checks: write

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version-file: 'go.mod'
        cache: true

    - name: Revive Action
      uses: morphy2k/revive-action@v2.4.1
      
    - name: Debug environment before Staticcheck
      run: |
        echo "PWD: $(pwd)"
        echo "Go version:"
        go version
        echo "Go env:"
        go env
        echo "Directory tree:"
        ls -R .

    - name: Staticcheck (debug)
      uses: dominikh/staticcheck-action@v1.3.0
      with:
        version: "latest"
      env:
        STATICCHECK_DEBUG: "1"

    - name: Build
      run: |
        go mod download
        go install gotest.tools/gotestsum@latest

    - name: Test
      run: |
        gotestsum --format=standard-verbose --junitfile=junit.xml

    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v3
      if: success() || failure() # always run even if the previous step fails
      with:
        report_paths: '**/junit.xml'
        detailed_summary: true
        include_passed: true
